
//Get all games
Get http://localhost:5139/games

###
//Get game by id
Get http://localhost:5139/games/7

###
//create a new game
POST http://localhost:5139/games
Content-Type: application/json

{
        "name": "GTA 3",
        "genreID": 1,
        "price": 29.99,
        "releaseDate": "2011-11-18"
}


###
//update a game
PUT http://localhost:5139/games/7
Content-Type: application/json

    {
        "name": "The Last Guardian",
        "genreId": 2,
        "price": 79.99,
        "releaseDate": "2016-04-12"
    }

###

DELETE http://localhost:5139/games/9

Delete