using System;
using GameStore.Api.DTOs;
using GameStore.Api.Entities;

namespace GameStore.Api.Mapping;

public static class GameMapping
{
    public static Game ToEntity(this CreateGameDto gameDto)
    {
        return new Game
        {
            ID = 0, // ID is auto-generated by the database
            Name = gameDto.Name,
            GenreID = gameDto.GenreID,
            Price = gameDto.Price,
            Release_Date = gameDto.ReleaseDate
        };
    }

    public static GameDto ToDto(this Game game)
    {
        return new
        (
            game.ID,
            game.Name,
            game.Genre!.Name,
            game.Price,
            game.Release_Date
        );
    }
}
